package com.edw.gis.bean;
// Generated May 13, 2013 9:46:58 AM by Hibernate Tools 3.2.1.GA



/**
 * Desa generated by hbm2java
 */
public class Desa  implements java.io.Serializable {


     private String id;
     private String idKecamatan;
     private String nama;

    public Desa() {
    }

	
    public Desa(String id) {
        this.id = id;
    }
    public Desa(String id, String idKecamatan, String nama) {
       this.id = id;
       this.idKecamatan = idKecamatan;
       this.nama = nama;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIdKecamatan() {
        return this.idKecamatan;
    }
    
    public void setIdKecamatan(String idKecamatan) {
        this.idKecamatan = idKecamatan;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


