package com.edw.gis.bean;
// Generated May 5, 2013 1:32:04 PM by Hibernate Tools 3.2.1.GA



/**
 * Kabupaten generated by hbm2java
 */
public class Kabupaten  implements java.io.Serializable {


     private String id;
     private String idProv;
     private String nama;

    public Kabupaten() {
    }

    public Kabupaten(String id, String idProv, String nama) {
       this.id = id;
       this.idProv = idProv;
       this.nama = nama;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIdProv() {
        return this.idProv;
    }
    
    public void setIdProv(String idProv) {
        this.idProv = idProv;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


