package com.edw.gis.bean;
// Generated May 5, 2013 1:32:04 PM by Hibernate Tools 3.2.1.GA



/**
 * Kecamatan generated by hbm2java
 */
public class Kecamatan  implements java.io.Serializable {


     private String id;
     private String idKabupaten;
     private String nama;

    public Kecamatan() {
    }

    public Kecamatan(String id, String idKabupaten, String nama) {
       this.id = id;
       this.idKabupaten = idKabupaten;
       this.nama = nama;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIdKabupaten() {
        return this.idKabupaten;
    }
    
    public void setIdKabupaten(String idKabupaten) {
        this.idKabupaten = idKabupaten;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


