package com.edw.gis.bean;
// Generated May 5, 2013 1:32:04 PM by Hibernate Tools 3.2.1.GA



/**
 * Provinsi generated by hbm2java
 */
public class Provinsi  implements java.io.Serializable {


     private String id;
     private String nama;

    public Provinsi() {
    }

    public Provinsi(String id, String nama) {
       this.id = id;
       this.nama = nama;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


